name: Stream Recorder

on:
  repository_dispatch:
    types: [start-record]
  workflow_dispatch:
    inputs:
      url:
        description: 'Ссылка на видео/стрим'
        required: true
        default: 'https://www.youtube.com/watch?v=aqz-KE-bpKQ'
      id:
        description: 'ID видео'
        required: true
        default: 'test_video'

jobs:
  record-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Установка софта (yt-dlp, ffmpeg, rclone)
        run: |
          sudo apt-get update && sudo apt-get install -y ffmpeg curl
          sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
          sudo chmod a+rx /usr/local/bin/yt-dlp
          sudo -v ; curl https://rclone.org/install.sh | sudo bash

      - name: Запись стрима / скачивание
        run: |
          TARGET_URL="${{ github.event.client_payload.url || github.event.inputs.url }}"
          TARGET_ID="${{ github.event.client_payload.id || github.event.inputs.id }}"
          
          echo "Работаем с видео: $TARGET_URL"
          
          # Маскируемся под iOS/Android клиент, чтобы YouTube не требовал подтверждения
          yt-dlp \
            --extractor-args "youtube:player_client=ios,web" \
            --no-part \
            -f "best[ext=mp4]/best" \
            -o "stream_${TARGET_ID}.%(ext)s" \
            "$TARGET_URL"

      - name: Настройка Rclone для Google Диска
        if: always()
        env:
          RCLONE_CONF_DATA: ${{ secrets.RCLONE_CONFIG_DATA }}
        run: |
          mkdir -p ~/.config/rclone
          printf "%s\n" "$RCLONE_CONF_DATA" > ~/.config/rclone/rclone.conf

      - name: Отправка на Google Диск
        if: always()
        run: |
          rclone copy ./ gdrive:YouTube_Records/ --include "stream_*.mp4" --include "stream_*.mkv" -v
